// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs"

import { config } from "dotenv"
import { defineConfig } from "prisma/config"

config()

if (existsSync(".env.local")) {
  config({ path: ".env.local", override: true })
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
